language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
script: ./test.sh
after_script:
  - coverage xml
  - python-codacy-coverage -r coverage.xml
